name: widget_tests
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.16
  flutter_modular: ^5.0.3
  flutter_dotenv: ^5.0.2
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - test/.env

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png